language: cpp

compiler:
    - clang

before_install:
  - pwd
  - mkdir ~/debug
  - cd ~/debug
  - cmake ~/build/masc-ucsc/lgraph
  - which clang

install:
  - make

before_script:
  - make clean

script:
- make test
