sudo: required

language: ruby

services:
  - docker

env:
  matrix:
    - BUILD_MODE=fastbuild DOCKER=mascucsc/archlinux-masc DOCKER_LGRAPH_SRC=/root/lgraph      LGRAPH_COMPILER=g++
    - BUILD_MODE=dbg       DOCKER=mascucsc/archlinux-masc DOCKER_LGRAPH_SRC=/root/lgraph      LGRAPH_COMPILER=clang++
    - BUILD_MODE=fastbuild DOCKER=mascucsc/alpine-masc    DOCKER_LGRAPH_SRC=/home/user/lgraph LGRAPH_COMPILER=g++
    - BUILD_MODE=dbg       DOCKER=mascucsc/ubuntu-masc    DOCKER_LGRAPH_SRC=/root/lgraph      LGRAPH_COMPILER=g++

before_install:
   - docker pull $DOCKER

script:
  - scripts/run-docker-test.sh `pwd` $BUILD_MODE $DOCKER $DOCKER_LGRAPH_SRC $LGRAPH_COMPILER

cache:
  directories:
    - $HOME/.cache/bazel
