sudo: required

language: cpp

services:
  - docker

env:
  matrix:
    - BUILD_TYPE=Release DOCKER=mascucsc/archlinux-masc
    - BUILD_TYPE=Debug   DOCKER=mascucsc/archlinux-masc
      #- BUILD_TYPE=Release DOCKER=mascucsc/ubuntu-masc
      #- BUILD_TYPE=Debug   DOCKER=mascucsc/ubuntu-masc

before_install:
  - docker pull mascucsc/archlinux-masc
  - docker pull mascucsc/ubuntu-masc

script:
  - misc/scripts/run-docker-test.sh `pwd` $BUILD_TYPE $DOCKER

