sudo: required

language: cpp

services:
  - docker

env:
  matrix:
    - BUILD_MODE=fastbuild DOCKER=mascucsc/archlinux-masc
    - BUILD_MODE=dbg       DOCKER=mascucsc/archlinux-masc
    - BUILD_MODE=fastbuild DOCKER=mascucsc/alpine-masc    DOCKER_LGRAPH_SRC=/home/user/lgraph
    - BUILD_MODE=dbg       DOCKER=mascucsc/ubuntu-masc

before_install:
   - docker pull $DOCKER
     # - docker pull mascucsc/archlinux-masc
  # - docker pull mascucsc/ubuntu-masc

script:
  - scripts/run-docker-test.sh `pwd` $BUILD_MODE $DOCKER $DOCKER_LGRAPH_SRC

