language: cpp

compiler:
    - clang

before_install:
  - mkdir ~/debug
  - cd ~/debug
  - which clang
  - cmake ~/build/masc-ucsc/lgraph -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

install:
  - make

before_script:
  - make clean

script:
- make test
