language: cpp

compiler:
    - clang

before_install:
  - mkdir ~/debug
  - cd ~/debug
  - which clang
  - export CXX=${COMPILER}
  - export CC=${COMPILER}
  - cmake ~/build/masc-ucsc/lgraph

install:
  - make

before_script:
  - make clean

script:
- make test
